### PR TITLE
Add custom record file name with current date and time

### PR DESCRIPTION
**Pull request by cxselph**
File name will be formatted like the following.  20190331_0830

### CODE REVIEW

**Comment by krocheck** [comment]
@cxselph you don't need to include a name prefix with this scheme?

**Comment by cxselph** [comment]
@krocheck Anything else?

**Comment by krocheck** [comment]
@cxselph I wasn't clear with what I meant.  I suppose I'm surprised for this naming convention that you don't need "camera1_20190331_0830" where "camera1" is a file name prefix ... that just the date is all you need in the file names.  You do need to revert the change you just made though.

**Comment by cxselph** [comment]
I don't have the ability to record iso's yet, just pgm out. Saving up for more hyper decks. I record 4 different services at my church over the weekend and I like to know what day and service based on time that I have when I need it.

**Comment by cxselph** [comment]
@krocheck Let me add a textbox option that will allow a name prefix if we need it or leave it blank if we don't.

**Comment by cxselph** [comment]
@krocheck I added the prefix option. Let me know if you need changes or have any other suggestions.

**Comment by krocheck** [comment]
@cxselph were you able to test these?

**Comment by cxselph** [comment]
@krocheck I did test the earlier version with no prefix options and it worked fine. The remote enable/disable worked fine. I will need to test the prefix addition tuesday when I get back to the office.

**Comment by krocheck** [comment]
Ok.  I may get to that before you, as I'm on-site with some hyperdecks tomorrow.

**Pull request merged**
