### PR TITLE
Use hyperdeck-connection

### PR DESCRIPTION
**Pull request by baltedewit**
For NRK's Sofie project a connection library for the Blackmagic Design Hyperdeck devices was developed. This connection library takes care of reconnection, resending and serialization/deserialization. In addition it also has an events system in place for notifications.

The current implementation in this module has no concept of connection status, commands or notifications. Using hyperdeck-connection will greatly improve the resiliency towards network errors of this module. In addition it will make it easier to add feedback in a future PR.

What is left to do
- [x] Release hyperdeck-connection with new commands added for companion
- [x] Test new implementation with companion and a hyperdeck

### CODE REVIEW

**Comment by haakonnessjoen** [comment]
I'm not sure if I am totally agreeing with you that the current module has no concept of connection status? It is done by the tcp library it uses. And effected by the on('status_change') event handler.

So it will probably not do much for network error resilency. But the other stuff is nice additions :) Go for it!

**Comment by baltedewit** [comment]
> I'm not sure if I am totally agreeing with you that the current module has no concept of connection status? It is done by the tcp library it uses. And effected by the on('status_change') event handler.

Yeah, I misworded that. What I meant is that I believe it doesn't use TCP keepalive nor use the hyperdeck ping mechanism.

**Comment by krocheck** [comment]
@baltedewit have you experienced issues with the TCP connectivity to a hyperdeck with Companion?  Because I've never had issues with this module in that regard.

Plus I'm in the middle of a re-write to add model detection and feedback, which for simplicity I added as index.js while leaving the existing file for the time being (https://github.com/bitfocus/companion-module-hyperdeck/blob/master/index.js).  So, your version bump to v1.2 is not necessary since v1.1 is the unreleased WIP.

Given this product has its interface documented and its relatively simple compared to something like ATEM which is quite complex and has to be reverse engineered ... I'm not seeing much gains by shifting over to a connection library.  If the TCP library in the project isn't up to snuff, I'd rather see time and effort put into bolstering that vs. side-stepping it since most modules don't have the convenience of a third-party library and lot of modules do use our internal library (such as the rest of the BMD modules).  But that all is not really my call, just my opinion.

**Comment by haakonnessjoen** [comment]
Not to be negative @baltedewit, but the update to use your module does not really do anything as far as I can see. There is no tcpkeepalive in your module, and it would be as easy to add that flag to our own tcp system, so that all the other modules in companion using the general tcp module, also will benefit from it. So the only thing new is the notifications of changes. But you are not really using them in the pull request. So nothing added there either. If @krocheck is adding feedback support, then that is in fact a good change I would like :) Hope you are not taking this in a negative manner, really thanks for the effort!

**Comment by baltedewit** [comment]
I think you would gain a lot from both having a shared codebase with us and also having a more structured approach to parsing responses (async and sync).

I'd be up for spending a few more hours implementing feedback, but I can't be spending energy on discussions like using libraries or not etc. Sorry to hear you guys are not up for collaboration on this one.

**Comment by haakonnessjoen** [comment]
Again, I think you are misunderstanding where I am coming from. But as far as I understood, krocheck has already done a lot of work with implementing data to/from the device and started on feedback handling. So it’s a bit up to him, if he wants to reimplement it using your module or not. I agree that a shared codebase could be good :) @krocheck decides :)

**Comment by krocheck** [comment]
Let me digest this a little more because I didn't see the standing PR in the library to add things like the play command.  I was sifting through the code noting to myself that it felt incomplete but missed that.

**Comment by krocheck** [comment]
@baltedewit this is still good to go?

**Comment by baltedewit** [comment]
Yeap, this one should be good!

**Pull request merged**
